apps/food/urls.py
from django.urls import path
from . import views

app_name = 'food'
urlpatterns = [
    path('', views.index, name='index'),
    path('item/', views.item, name='item'),
    path('detail/<int:item_id>', views.detail, name='detail'),
    path('add-item', views.add_item, name='add_item'),
    path('update-item/<int:item_id>', views.update_item, name='update_item'),
    path('delete-item/<int:item_id>', views.delete_item, name='delete_item'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import include, path
from apps.users import views as users_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('apps.food.urls')),
    path('users/', users_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(
        template_name='users/login.html'
    ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='users/logout.html'
    ), name='logout'),
    path('profile/', users_views.profile_page, name='profile'),
] 

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/food/models.py
from django.db import models

# Create your models here.

class Item(models.Model):
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.FloatField(default=0)
    image_url = models.CharField(
        max_length=500, 
        default='https://upload.wikimedia.org/wikipedia/commons/6/62/Image_unavailable.png'
    )

    def __str__(self):
        return f'Name {self.item_name}, $ {self.item_price:.2f}'

apps/users/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(
        default='profilepic.png',
        upload_to='profile_pictures'
    )
    location = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.user.username}'

apps/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'item_name',
            'item_desc',
            'item_price', 
            'image_url',
        ]

apps/users/forms.py
from django import forms 
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2',
        ]

apps/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from .forms import ItemForm

# Create your views here.
def index(request):
    item_list = Item.objects.all()
    context = {'item_list': item_list,}

    return render(request, 'food/index.html', context)

def item(request):
    return HttpResponse('This is an item view')

def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {'item': item,}
    return render(request, 'food/detail.html', context)

def add_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-form.html', {'form': form})

def update_item(request, item_id):
    item = Item.objects.get(id=item_id)
    
    form = ItemForm(request.POST or None, instance=item)
    
    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/item-form.html', {'form': form})

def delete_item(request, item_id):
    item = Item.objects.get(id=item_id)
    
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request, 'food/item-delete.html', {'item': item})

apps/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages 
from django.contrib.auth.decorators import login_required
from .forms import RegisterForm

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            user_name = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {user_name}, your account is created!')
            return redirect('food:index')
    else:
        form = RegisterForm()        

    return render(request, 'users/register.html', {'form': form})

@login_required
def profile_page(request):
    return render(request, 'users/profile.html')

apps/food/templates/food/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary bg-primary" data-bs-theme="dark" >
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Good Food</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'food:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'food:add_item' %}">Add Item</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>                    
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    {% endif %}

                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                    </li>                    
                    {% endif %}

                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}

    {% block body %}
    {% endblock %}
</body>

</html>

apps/food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}

{% if item %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img class="img-fluid max-height-50" src="{{ item.image_url }}" alt="{{ item.item_desc }}">
        </div>
        <div class="col-md-6">
            <h1>{{ item.item_name }}</h1>
            <h2>{{ item.item_desc }}</h2>
            <h3>${{ item.item_price }}</h3>
            <a class="btn btn-danger" href="{% url 'food:delete_item' item.id %}" role="button">Delete</a>
        </div>
    </div>
</div>

{% endif %}
<a class="btn btn-success" href="{% url 'food:index' %}" role="button">Voltar</a>
{% endblock %}

apps/food/templates/food/index.html
{% extends 'food/base.html' %}
{% load static %}

<body>
    {% block body %}

    {% if item_list %}
        {% for item in item_list %}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card img-fluid max-height-50" src="{{ item.image_url }}" alt="{{ item.item_desc }}">
            </div>

            <div class="col-md-4">
                <h3>{{ item.item_name }}</h3>
                <h5>{{ item.item_desc }}</h5>
                <h6>${{ item.item_price }}</h6>
            </div>

            <div class="col-md-2">
                <a class="btn btn-success" href="{% url 'food:detail' item.id %}" role="button">Details</a>
            </div>
        </div>

        {% endfor %}
    {% endif %}
    {% endblock %}

</body>

apps/food/templates/food/item-delete.html
{% extends 'food/base.html' %}
{% block body %}

<form action="" method="POST">
    {% csrf_token %}
    {{ form }}

    <h3>Are you sure you want delete {{ item.item_name }}?</h3>
    <button type="submit" class="btn btn-danger">Confirm</button>
</form>

<a class="btn btn-success" href="{% url 'food:index' %}" role="button">Voltar</a>
{% endblock %}

apps/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}

<form action="" method="POST">
    {% csrf_token %}
    {{ form }}

    <button type="submit">Save</button>
</form>

<a class="btn btn-success" href="{% url 'food:index' %}" role="button">Voltar</a>
{% endblock %}

apps/users/templates/users/login.html
<form action="" method="POST">
    {% csrf_token %}
    {{ form }}

    <button type="submit">Signup</button>
</form>

apps/users/templates/users/logout.html
<h1>You have been logged out</h1>

apps/users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img src="{{ user.profile.image.url }}" alt="Profile picture">

<a class="btn btn-success" href="{% url 'food:index' %}" role="button">Voltar</a>

apps/users/templates/users/register.html
<form action="" method="POST">
    {% csrf_token %}
    {{ form }}

    <button type="submit">Signup</button>
</form>